logging:
  level: info
aws:
   secrets: "dev/secrets"
   bucketName: chux-crawler
   downloadPath: /home/csailer/projects/chux/chux-parser/app/data
   archiveBucket: chux-crawler-arch
auth:
  issuerUrl: https://dev-29752729.okta.com/oauth2/default
  tokenUrl: ""
data:
   path: "/home/csailer/projects/chux/chux-parser/data"
dataStores:
  dataStore:
    mongo:
      target: mongo
      uri: mongodb+srv://<username>:<password>@chux-mongo-cluster.4mvs7.mongodb.net/chux-cprs
      timeout: 10
      databaseName: chux-cprs
      collectionName: ""
    redis:
      target: redis
      uri: redis://localhost:6379
      timeout: 5
      databaseName: your-redis-database-name
      collectionName: your-redis-collection-name
productSources:
  - ebay
  - sweetwater
  - perfectcircuit
  - reverb
  - thomann
  - zzounds
  - samash
  - guitarcenter
  - musiciansfriend
  - thomannmusic